#!/bin/sh

# Prepare LIWC dictionaries:
python3 src/liwc_cleaning.py

# Train Sentiment classifier
nohup python3 -u src/setup_emb_clf.py --overwrite_embeddings True > emb_clf.out &

# Run sentiment imputation
python3 src/main_sentiment_imputer.py 20200101 --data_path ~/data-lake/twitter/processed/ --dict_methods liwc emoji --emb_methods bert

# Run aggregation:

## Politics topical subsets
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords biden --name_ext biden > agg_biden.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords trump --name_ext trump > agg_trump.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --name_ext election_1month > agg_USA1_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --name_ext election_3month > agg_USA1_3month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --name_ext election_1month > agg_USA2_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --name_ext election_3month > agg_USA2_3month.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --incl_keywords biden --name_ext biden_1month > agg_biden1_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords biden --name_ext biden_3month > agg_biden1_3month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --incl_keywords biden --name_ext biden_1month > agg_biden2_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords biden --name_ext biden_3month > agg_biden2_3month.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --incl_keywords trump --name_ext trump_1month > agg_trump1_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords trump --name_ext trump_3month > agg_trump1_3month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-09-01 --end_date 2020-09-30 --incl_keywords trump --name_ext trump_1month > agg_trump2_1month.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin2 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-07-01 --end_date 2020-09-30 --incl_keywords trump --name_ext trump_3month > agg_trump2_3month.out &

## Topical subsets
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-05-01 --end_date 2020-09-30 --incl_keywords 'black\slives\smatter' '\bblm\b' 'blacklivesmatter' --name_ext black_lives_matter > agg_blm.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-05-01 --end_date 2020-09-30 --incl_keywords 'black\slives\smatter' '\bblm\b' 'blacklivesmatter' --name_ext black_lives_matter > agg_blm_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-05-01 --end_date 2020-09-30 --incl_keywords 'black\slives\smatter' '\bblm\b' 'blacklivesmatter' --name_ext black_lives_matter > agg_blm1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-05-01 --end_date 2020-09-30 --incl_keywords 'green\snew\sdeal' '\bgnd\b' 'greennewdeal' --name_ext green_new_deal > agg_greennewdeal.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-05-01 --end_date 2020-09-30 --incl_keywords 'green\snew\sdeal' '\bgnd\b' 'greennewdeal' --name_ext green_new_deal > agg_greennewdeal_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords 'green\snew\sdeal' '\bgnd\b' 'greennewdeal' --name_ext green_new_deal > agg_greennewdeal1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords '\bcapitalism' --name_ext capitalism > agg_capitalism.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords '\bcapitalism' --name_ext capitalism > agg_capitalism_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords '\bcapitalism' --name_ext capitalism > agg_capitalism1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-07-01 --end_date 2020-09-30 --incl_keywords 'supreme\scourt' 'supremecourt' '\bsotus\b' --name_ext supreme_court > agg_sotus.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-07-01 --end_date 2020-09-30 --incl_keywords 'supreme\scourt' 'supremecourt' '\bsotus\b' --name_ext supreme_court > agg_sotus_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords 'supreme\scourt' 'supremecourt' '\bsotus\b' --name_ext supreme_court > agg_sotus1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'climate\schange' 'climatechange' --name_ext climate_change > agg_climatechange.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'climate\schange' 'climatechange' --name_ext climate_change > agg_climatechange_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords 'climate\schange' 'climatechange' --name_ext climate_change > agg_climatechange1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'universal\shealth\s?care' 'universalhealthcare' --name_ext u_healthcare > agg_u_healthcare.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'universal\shealth\s?care' 'universalhealthcare' --name_ext u_healthcare > agg_u_healthcare_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords 'universal\shealth\s?care' 'universalhealthcare' --name_ext u_healthcare > agg_u_healthcare1.out &

nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'single\s?payer\s?health\s?care' --name_ext singlepayer_healthcare > agg_singlepayer_healthcare.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level country --time_level day --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2019-01-01 --end_date 2020-09-30 --incl_keywords 'single\s?payer\s?health\s?care' --name_ext singlepayer_healthcare > agg_singlepayer_healthcare_day.out &
nohup python3 -u src/main_sentiment_aggregator.py USA --geo_level admin1 --time_level all --tweet_text_path /home/sentiment/data-lake/twitter/processed/ --tweet_geo_path /home/sentiment/data-lake/twitter/geoinfo/ --start_date 2020-01-01 --end_date 2020-09-30 --incl_keywords 'single\s?payer\s?health\s?care' --name_ext singlepayer_healthcare > agg_singlepayer_healthcare1.out &
